### PR TITLE
FT-1819-truncate/round-age-down-for-patientdimension

### PR DESCRIPTION
**Pull request by cdejonge**
Age will be floor-ed for storing it in PatientDimension (just as we humans do).
Age as Observation is unchanged.

### CODE REVIEW

**Comment by cataphract** [comment]
1) Instead of assuming that AGE is the only demographic variable, it would be better to actually test that the variable in question is AGE, rather than testing whether its numeric.

2) Please fix the codenarc violations and 3) add a test case that ensures the rounding is happening (unit or functional). See the README on how to run checks and tests.

**Comment by cdejonge** [comment]
Good points. I will give it a try.
Don't know which codenarc rules I violated. Is there a way to check this. Tried to add the codenarc plugin into IntelliJ without succes "failed to initialize"

**Comment by cataphract** [comment]
Run `./gradlew check`

**Comment by cdejonge** [comment]
Thnx for setting me in the right direction. I will look at the tests next week.

**Comment by cdejonge** [comment]
@cataphract Do you expect me to do something for this pull-request before it can be accepted?

**Comment by forus** [comment]
Merged by https://github.com/thehyve/transmart-batch/pull/88

**Pull request closed without merging**
